# Generated by Django 3.1.4 on 2021-01-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApp', '0002_bill_date_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='Done',
            field=models.BooleanField(default=False),
        ),
    ]
