# Generated by Django 3.1.4 on 2021-01-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApp', '0003_bill_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='Date_In',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date In'),
        ),
    ]
