# Generated by Django 3.1.4 on 2021-01-20 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApp', '0004_auto_20210101_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery_in',
            name='client',
        ),
    ]
