# Generated by Django 3.1.4 on 2021-01-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApp', '0005_remove_delivery_in_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='end_client',
        ),
        migrations.AddField(
            model_name='bill',
            name='endClientName',
            field=models.CharField(default='Unknown Name', max_length=100000),
        ),
        migrations.AddField(
            model_name='bill',
            name='endClientNumber',
            field=models.CharField(default='03000000', max_length=10000),
        ),
        migrations.DeleteModel(
            name='EndClient',
        ),
    ]
