# Generated by Django 3.1.4 on 2021-01-20 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApp', '0007_remove_client_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery_in',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='delivery_out',
            name='Location',
        ),
    ]
