# Generated by Django 3.1.4 on 2021-01-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApp', '0008_auto_20210120_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='Date_Sent',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date In'),
        ),
    ]
