# Generated by Django 3.1.4 on 2021-01-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApp', '0011_auto_20210121_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='Hidden_Status',
            field=models.CharField(choices=[('paid', 'PAID'), ('pending', 'PENDING'), ('sent', 'SENT'), ('refunded', 'REFUNDED')], default='pending', max_length=99),
        ),
    ]
