# Generated by Django 3.1.4 on 2021-02-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApp', '0012_bill_hidden_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='Done_Refunding',
            field=models.BooleanField(default=False),
        ),
    ]
