# Generated by Django 3.1.4 on 2021-03-01 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApp', '0013_bill_done_refunding'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Report', models.CharField(blank=True, default='No Report', max_length=100000000)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveryApp.client')),
            ],
        ),
    ]
