# Generated by Django 3.1.4 on 2021-03-02 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApp', '0015_auto_20210302_0245'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportLog',
        ),
    ]
