# Generated by Django 2.1.3 on 2021-03-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApp', '0016_delete_reportlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='Date_Done',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date Done'),
        ),
        migrations.AddField(
            model_name='bill',
            name='Date_Paid',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date Paid'),
        ),
    ]
