# Generated by Django 2.1.3 on 2021-03-07 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApp', '0017_auto_20210307_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='Date',
        ),
    ]
